# Generated by Django 3.0.4 on 2022-06-22 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_link', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('group', models.CharField(choices=[('journal', 'Journal'), ('publication', 'Publication'), ('book', 'Book'), ('conference_article', 'Conference Article'), ('report', 'Report'), ('misc_paper', 'Miscellaneous Papers')], max_length=20)),
                ('level', models.CharField(choices=[('', 'None'), ('national', 'National'), ('international', 'International')], default='national', max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('authors', models.CharField(blank=True, max_length=250, null=True)),
                ('author_status', models.CharField(choices=[('', 'None'), ('chief', 'Chief'), ('correspondence', 'Correspondence'), ('co-author', 'Co-Author')], default='chief', max_length=20, null=True)),
                ('journal', models.CharField(blank=True, max_length=250, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('peer_reviewed', models.CharField(blank=True, max_length=50, null=True)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('SJR_rating', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('impact_factor_journal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('DOI', models.CharField(blank=True, max_length=50, null=True)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('chapters', models.CharField(blank=True, max_length=50, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('organised_date', models.DateField(blank=True, default=models.DateField(blank=True, null=True), null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publication_date',),
            },
        ),
    ]
